name: XcodeGen-Demo

options:
  bundleIdPrefix: com.kazua
  deploymentTarget:
    iOS: 13.0
  developmentLanguage: ja

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    version: 5.4.0

targets:
  XcodeGen-Demo:
    type: application
    platform: iOS
    sources:
      - XcodeGen-Demo
    settings:
      base:
        INFOPLIST_FILE: XcodeGen-Demo/Application/Info.plist
        DEVELOPMENT_LANGUAGE: jp
    dependencies:
      - package: Alamofire
    postCompileScripts:
      - path: ./Scripts/XcodeGen/swiftlint.sh
        name: Run SwiftLint

schemes:
  XcodeGen-Demo:
    build:
      targets:
        XcodeGen-Demo: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
